export ZSH=$HOME/.zsh

setopt share_history
setopt hist_ignore_space
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify

setopt ignoreeof
setopt auto_cd
setopt multios
setopt prompt_subst

autoload -U colors && colors
source $ZSH/git.zsh
source $ZSH/completion.zsh
source $ZSH/tarcadia.zsh-theme

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if command diff --color /dev/null /dev/null &>/dev/null; then
  alias diff='diff --color'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias zshconfig="mate ~/.zshrc"
alias please='sudo -E'

. /etc/zsh_command_not_found

figlet -f slant Hello Tarcadia! | lolcat

